name: Github action user input

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        run: echo "Hello, ${{ github.event.inputs.name }}!"
